name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Add SPA redirect script to 404.html
        run: |
          REDIRECT_SCRIPT='<script>
          // https://github.com/rafgraph/spa-github-pages
          (function(l) {
            if (l.search[1] === "/") {
              var decoded = l.search.slice(1).split("&").map(function(s) {
                return s.replace(/~and~/g, "&")
              }).join("?");
              window.history.replaceState(null, null,
                l.pathname.slice(0, -1) + decoded + l.hash
              );
            }
          }(window.location));
          </script>'
          # Füge das Skript vor </head> in 404.html ein
          awk -v script="$REDIRECT_SCRIPT" '/<\/head>/ {print script} 1' dist/404.html > dist/404_tmp.html && mv dist/404_tmp.html dist/404.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
