name: Quality Gate & Testing

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    name: Code Quality & Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type checking
        run: npm run type-check

      - name: ESLint check
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Run tests
        run: npm test

      - name: Build check
        run: npm run build
